In [7]:
import pandas as pd


df = pd.read_csv("data/Mercancias-RESUMEN.csv", sep=";")
df

,Año,Autoridad Portuaria,Operacion,Transito,Graneles líquidos,Graneles sólidos,Mercancía general convencional,Mercancía general en contenedor,Mercancía general,Pesca,Avituallamiento,Tráfico interior,TRÁFICO TOTAL,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,1962,A Coruña,Desembarque,Incluido tránsito,204.092,147.137,110.979,0,110.979,71.917,0,6.319,540.444,NaN,NaN,NaN
1,1962,A Coruña,Embarque,Incluido tránsito,6.088,357.934,48.127,0,48.127,0.000,246.628,144,658.921,NaN,NaN,NaN
2,1962,Alicante,Desembarque,Incluido tránsito,148.633,465.540,269.215,0,269.215,5.932,0,0,889.320,NaN,NaN,NaN
3,1962,Alicante,Embarque,Incluido tránsito,0,54.872,194.343,0,194.343,0.000,31,0,249.246,NaN,NaN,NaN
4,1962,Almería,Desembarque,Incluido tránsito,97.697,161.995,37.804,0,37.804,9.631,0,0,307.127,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5820,2024,Vilagarcía,Desembarque,Incluido tránsito,286.257,321.986,229.202,56.521,285.723,0.000,0,0,893.966,NaN,NaN,NaN
5821,2024,Vilagarcía,Desembarque,Solo tránsito,0,2.954,0,906,906,0.000,0,0,3.860,NaN,NaN,NaN
5822,2024,Vilagarcía,Embarque,Incluido tránsito,0,90.391,210.000,213.240,423.240,0.000,8.386,0,522.017,NaN,NaN,NaN
5823,2024,Vilagarcía,Embarque,Solo tránsito,0,0,0,883,883,0.000,0,0,883,NaN,NaN,NaN
5824,2024,Vilagarcía,Transbordo,Incluido tránsito,0,0,0,0,0,0.000,0,0,0,NaN,NaN,NaN

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5825 entries, 0 to 5824
Data columns (total 16 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Año                              5825 non-null   datetime64[us]
 1   Autoridad Portuaria              5825 non-null   str
 2   Operacion                        5825 non-null   str
 3   Transito                         5825 non-null   str
 4   Graneles líquidos                5825 non-null   str
 5   Graneles sólidos                 5825 non-null   str
 6   Mercancía general convencional   5825 non-null   str
 7   Mercancía general en contenedor  5825 non-null   str
 8   Mercancía general                5825 non-null   str
 9   Pesca                            5825 non-null   float64
 10  Avituallamiento                  5825 non-null   str
 11  Tráfico interior                 5825 non-null   str
 12  TRÁFICO TOTAL                    5825 non-null   str
 13  Unnamed: 13                      0 non-null      float64
 14  Unnamed: 14                      0 non-null      float64
 15  Unnamed: 15                      0 non-null      float64
dtypes: datetime64[us](1), float64(4), str(11)
memory usage: 728.3 KB

In [9]:
df["Año"] = pd.to_datetime(df["Año"], format="%Y")

In [11]:
df_filtrado = df[df["Año"].dt.year.isin([2023, 2024])]
df_filtrado

,Año,Autoridad Portuaria,Operacion,Transito,Graneles líquidos,Graneles sólidos,Mercancía general convencional,Mercancía general en contenedor,Mercancía general,Pesca,Avituallamiento,Tráfico interior,TRÁFICO TOTAL,Unnamed: 13,Unnamed: 14,Unnamed: 15
5545,2023-01-01,A Coruña,Desembarque,Incluido tránsito,5.724.746,3.465.159,429.305,132,429.437,27.034,0,0,9.646.376,NaN,NaN,NaN
5546,2023-01-01,A Coruña,Desembarque,Solo tránsito,0,713.357,0,0,0,0.000,0,0,713.357,NaN,NaN,NaN
5547,2023-01-01,A Coruña,Embarque,Incluido tránsito,2.350.208,1.755.532,147.836,41,147.877,0.000,75.448,0,4.329.065,NaN,NaN,NaN
5548,2023-01-01,A Coruña,Embarque,Solo tránsito,0,1.001.518,0,0,0,0.000,0,0,1.001.518,NaN,NaN,NaN
5549,2023-01-01,A Coruña,Transbordo,Incluido tránsito,0,7.012,0,0,0,0.000,0,0,7.012,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5820,2024-01-01,Vilagarcía,Desembarque,Incluido tránsito,286.257,321.986,229.202,56.521,285.723,0.000,0,0,893.966,NaN,NaN,NaN
5821,2024-01-01,Vilagarcía,Desembarque,Solo tránsito,0,2.954,0,906,906,0.000,0,0,3.860,NaN,NaN,NaN
5822,2024-01-01,Vilagarcía,Embarque,Incluido tránsito,0,90.391,210.000,213.240,423.240,0.000,8.386,0,522.017,NaN,NaN,NaN
5823,2024-01-01,Vilagarcía,Embarque,Solo tránsito,0,0,0,883,883,0.000,0,0,883,NaN,NaN,NaN
5824,2024-01-01,Vilagarcía,Transbordo,Incluido tránsito,0,0,0,0,0,0.000,0,0,0,NaN,NaN,NaN

In [12]:
df_filtrado.drop(columns=["Unnamed: 13", "Unnamed: 14", "Unnamed: 15"])

,Año,Autoridad Portuaria,Operacion,Transito,Graneles líquidos,Graneles sólidos,Mercancía general convencional,Mercancía general en contenedor,Mercancía general,Pesca,Avituallamiento,Tráfico interior,TRÁFICO TOTAL
5545,2023-01-01,A Coruña,Desembarque,Incluido tránsito,5.724.746,3.465.159,429.305,132,429.437,27.034,0,0,9.646.376
5546,2023-01-01,A Coruña,Desembarque,Solo tránsito,0,713.357,0,0,0,0.000,0,0,713.357
5547,2023-01-01,A Coruña,Embarque,Incluido tránsito,2.350.208,1.755.532,147.836,41,147.877,0.000,75.448,0,4.329.065
5548,2023-01-01,A Coruña,Embarque,Solo tránsito,0,1.001.518,0,0,0,0.000,0,0,1.001.518
5549,2023-01-01,A Coruña,Transbordo,Incluido tránsito,0,7.012,0,0,0,0.000,0,0,7.012
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5820,2024-01-01,Vilagarcía,Desembarque,Incluido tránsito,286.257,321.986,229.202,56.521,285.723,0.000,0,0,893.966
5821,2024-01-01,Vilagarcía,Desembarque,Solo tránsito,0,2.954,0,906,906,0.000,0,0,3.860
5822,2024-01-01,Vilagarcía,Embarque,Incluido tránsito,0,90.391,210.000,213.240,423.240,0.000,8.386,0,522.017
5823,2024-01-01,Vilagarcía,Embarque,Solo tránsito,0,0,0,883,883,0.000,0,0,883
5824,2024-01-01,Vilagarcía,Transbordo,Incluido tránsito,0,0,0,0,0,0.000,0,0,0

In [13]:
df_filtrado["Autoridad Portuaria"].value_counts()

Autoridad Portuaria
A Coruña                     10
Alicante                     10
Almería                      10
Avilés                       10
Bahía de Algeciras           10
Bahía de Cádiz               10
Baleares                     10
Barcelona                    10
Bilbao                       10
Cartagena                    10
Castellón                    10
Ceuta                        10
Ferrol-San Cibrao            10
Gijón                        10
Huelva                       10
Las Palmas                   10
Marín y Ría de Pontevedra    10
Melilla                      10
Motril                       10
Málaga                       10
Pasaia                       10
Santa Cruz de Tenerife       10
Santander                    10
Sevilla                      10
Tarragona                    10
Valencia                     10
Vigo                         10
Vilagarcía                   10
Name: count, dtype: int64

In [14]:
df_bahiadecadiz = df_filtrado[df_filtrado["Autoridad Portuaria"] == "Bahía de Cádiz"]
df_bahiadecadiz

,Año,Autoridad Portuaria,Operacion,Transito,Graneles líquidos,Graneles sólidos,Mercancía general convencional,Mercancía general en contenedor,Mercancía general,Pesca,Avituallamiento,Tráfico interior,TRÁFICO TOTAL,Unnamed: 13,Unnamed: 14,Unnamed: 15
5570,2023-01-01,Bahía de Cádiz,Desembarque,Incluido tránsito,625.117,1.868.405,360.751,455.814,816.565,12.200,0,0,3.322.287,NaN,NaN,NaN
5571,2023-01-01,Bahía de Cádiz,Desembarque,Solo tránsito,563.549,26.110,3.554,103.231,106.785,0.000,0,0,696.444,NaN,NaN,NaN
5572,2023-01-01,Bahía de Cádiz,Embarque,Incluido tránsito,629.901,345.896,272.721,1.051.975,1.324.696,0.000,115.507,0,2.416.000,NaN,NaN,NaN
5573,2023-01-01,Bahía de Cádiz,Embarque,Solo tránsito,626.188,41.411,50,103.185,103.235,0.000,0,0,770.834,NaN,NaN,NaN
5574,2023-01-01,Bahía de Cádiz,Transbordo,Incluido tránsito,0,12.477,0,0,0,0.000,0,0,12.477,NaN,NaN,NaN
5710,2024-01-01,Bahía de Cádiz,Desembarque,Incluido tránsito,296.422,1.236.324,401.528,486.330,887.858,11.065,0,0,2.431.669,NaN,NaN,NaN
5711,2024-01-01,Bahía de Cádiz,Desembarque,Solo tránsito,235.175,13.309,21.962,113.131,135.093,0.000,0,0,383.577,NaN,NaN,NaN
5712,2024-01-01,Bahía de Cádiz,Embarque,Incluido tránsito,236.261,415.063,378.088,1.146.281,1.524.369,0.000,119.139,0,2.294.832,NaN,NaN,NaN
5713,2024-01-01,Bahía de Cádiz,Embarque,Solo tránsito,228.140,47.266,3.671,119.289,122.960,0.000,0,0,398.366,NaN,NaN,NaN
5714,2024-01-01,Bahía de Cádiz,Transbordo,Incluido tránsito,590,4.859,0,0,0,0.000,0,0,5.449,NaN,NaN,NaN