In [1]:
pip install requests beautifulsoup4 lxml

Requirement already satisfied: requests in c:\users\usuario\appdata\local\programs\python\python314\lib\site-packages (2.32.5)
Requirement already satisfied: beautifulsoup4 in c:\users\usuario\appdata\local\programs\python\python314\lib\site-packages (4.14.3)
Requirement already satisfied: lxml in c:\users\usuario\appdata\local\programs\python\python314\lib\site-packages (6.0.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\usuario\appdata\local\programs\python\python314\lib\site-packages (from requests) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in c:\users\usuario\appdata\local\programs\python\python314\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\usuario\appdata\local\programs\python\python314\lib\site-packages (from requests) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\usuario\appdata\local\programs\python\python314\lib\site-packages (from requests) (2026.2.25)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\usuario\appdata\local\programs\python\python314\lib\site-packages (from beautifulsoup4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\usuario\appdata\local\programs\python\python314\lib\site-packages (from beautifulsoup4) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import requests

url = "https://realpython.github.io/fake-jobs/"
response = requests.get(url)
html = response.text

In [3]:
html

'<!DOCTYPE html>\n<html>\n  <head>\n    <meta charset="utf-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1">\n    <title>Fake Python</title>\n    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">\n  </head>\n  <body>\n  <section class="section">\n    <div class="container mb-5">\n      <h1 class="title is-1">\n        Fake Python\n      </h1>\n      <p class="subtitle is-3">\n        Fake Jobs for Your Web Scraping Journey\n      </p>\n    </div>\n    <div class="container">\n    <div id="ResultsContainer" class="columns is-multiline">\n    <div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Senior Python Developer</h2>\n        <h3 class="subtitle is-6 company">Payne, Roberts and Davis</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        Stewartbury, AA\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/senior-python-developer-0.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Energy engineer</h2>\n        <h3 class="subtitle is-6 company">Vasquez-Davidson</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        Christopherville, AA\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/energy-engineer-1.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Legal executive</h2>\n        <h3 class="subtitle is-6 company">Jackson, Chambers and Levy</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        Port Ericaburgh, AA\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/legal-executive-2.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Fitness centre manager</h2>\n        <h3 class="subtitle is-6 company">Savage-Bradley</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        East Seanview, AP\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/fitness-centre-manager-3.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Product manager</h2>\n        <h3 class="subtitle is-6 company">Ramirez Inc</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        North Jamieview, AP\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/product-manager-4.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Medical technical officer</h2>\n        <h3 class="subtitle is-6 company">Rogers-Yates</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        Davidville, AP\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/medical-technical-officer-5.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Physiological scientist</h2>\n        <h3 class="subtitle is-6 company">Kramer-Klein</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        South Christopher, AE\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/physiological-scientist-6.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Textile designer</h2>\n        <h3 class="subtitle is-6 company">Meyers-Johnson</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        Port Jonathan, AE\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/textile-designer-7.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Television floor manager</h2>\n        <h3 class="subtitle is-6 company">Hughes-Williams</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        Osbornetown, AE\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/television-floor-manager-8.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Waste management officer</h2>\n        <h3 class="subtitle is-6 company">Jones, Williams and Villa</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        Scotttown, AP\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/waste-management-officer-9.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Software Engineer (Python)</h2>\n        <h3 class="subtitle is-6 company">Garcia PLC</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        Ericberg, AE\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/software-engineer-python-10.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Interpreter</h2>\n        <h3 class="subtitle is-6 company">Gregory and Sons</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        Ramireztown, AE\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/interpreter-11.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Architect</h2>\n        <h3 class="subtitle is-6 company">Clark, Garcia and Sosa</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        Figueroaview, AA\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/architect-12.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Meteorologist</h2>\n        <h3 class="subtitle is-6 company">Bush PLC</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        Kelseystad, AA\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/meteorologist-13.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Audiological scientist</h2>\n        <h3 class="subtitle is-6 company">Salazar-Meyers</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        Williamsburgh, AE\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/audiological-scientist-14.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">English as a second language teacher</h2>\n        <h3 class="subtitle is-6 company">Parker, Murphy and Brooks</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        Mitchellburgh, AE\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/english-as-a-second-language-teacher-15.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Surgeon</h2>\n        <h3 class="subtitle is-6 company">Cruz-Brown</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        West Jessicabury, AA\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/surgeon-16.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Equities trader</h2>\n        <h3 class="subtitle is-6 company">Macdonald-Ferguson</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        Maloneshire, AE\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/equities-trader-17.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="h

In [4]:
from bs4 import BeautifulSoup

sopa = BeautifulSoup(html, "lxml")

In [10]:
import requests
from bs4 import BeautifulSoup

url = "https://realpython.github.io/fake-jobs/"
response = requests.get(url)
sopa = BeautifulSoup(response.text, "lxml")

tarjetas = sopa.find_all("div", class_="card-content")

for t in tarjetas:
    titulo = t.find("h2", class_="title is-5").text.strip()
    empresa = t.find("h3", class_="subtitle is-6 company").text.strip()
    ubicacion = t.find("p", class_="location").text.strip()
    fecha = t.find("p", class_="is-small has-text-grey").text.strip()

    print(titulo, "-", empresa, "-", ubicacion, fecha)

Senior Python Developer - Payne, Roberts and Davis - Stewartbury, AA 2021-04-08
Energy engineer - Vasquez-Davidson - Christopherville, AA 2021-04-08
Legal executive - Jackson, Chambers and Levy - Port Ericaburgh, AA 2021-04-08
Fitness centre manager - Savage-Bradley - East Seanview, AP 2021-04-08
Product manager - Ramirez Inc - North Jamieview, AP 2021-04-08
Medical technical officer - Rogers-Yates - Davidville, AP 2021-04-08
Physiological scientist - Kramer-Klein - South Christopher, AE 2021-04-08
Textile designer - Meyers-Johnson - Port Jonathan, AE 2021-04-08
Television floor manager - Hughes-Williams - Osbornetown, AE 2021-04-08
Waste management officer - Jones, Williams and Villa - Scotttown, AP 2021-04-08
Software Engineer (Python) - Garcia PLC - Ericberg, AE 2021-04-08
Interpreter - Gregory and Sons - Ramireztown, AE 2021-04-08
Architect - Clark, Garcia and Sosa - Figueroaview, AA 2021-04-08
Meteorologist - Bush PLC - Kelseystad, AA 2021-04-08
Audiological scientist - Salazar-Meyers - Williamsburgh, AE 2021-04-08
English as a second language teacher - Parker, Murphy and Brooks - Mitchellburgh, AE 2021-04-08
Surgeon - Cruz-Brown - West Jessicabury, AA 2021-04-08
Equities trader - Macdonald-Ferguson - Maloneshire, AE 2021-04-08
Newspaper journalist - Williams, Peterson and Rojas - Johnsonton, AA 2021-04-08
Materials engineer - Smith and Sons - South Davidtown, AP 2021-04-08
Python Programmer (Entry-Level) - Moss, Duncan and Allen - Port Sara, AE 2021-04-08
Product/process development scientist - Gomez-Carroll - Marktown, AA 2021-04-08
Scientist, research (maths) - Manning, Welch and Herring - Laurenland, AE 2021-04-08
Ecologist - Lee, Gutierrez and Brown - Lauraton, AP 2021-04-08
Materials engineer - Davis, Serrano and Cook - South Tammyberg, AP 2021-04-08
Historic buildings inspector/conservation officer - Smith LLC - North Brandonville, AP 2021-04-08
Data scientist - Thomas Group - Port Robertfurt, AA 2021-04-08
Psychiatrist - Silva-King - Burnettbury, AE 2021-04-08
Structural engineer - Pierce-Long - Herbertside, AA 2021-04-08
Immigration officer - Walker-Simpson - Christopherport, AP 2021-04-08
Python Programmer (Entry-Level) - Cooper and Sons - West Victor, AE 2021-04-08
Neurosurgeon - Donovan, Gonzalez and Figueroa - Port Aaron, AP 2021-04-08
Broadcast engineer - Morgan, Butler and Bennett - Loribury, AA 2021-04-08
Make - Snyder-Lee - Angelastad, AP 2021-04-08
Nurse, adult - Harris PLC - Larrytown, AE 2021-04-08
Air broker - Washington PLC - West Colin, AP 2021-04-08
Editor, film/video - Brown, Price and Campbell - West Stephanie, AP 2021-04-08
Production assistant, radio - Mcgee PLC - Laurentown, AP 2021-04-08
Engineer, communications - Dixon Inc - Wrightberg, AP 2021-04-08
Sales executive - Thompson, Sheppard and Ward - Alberttown, AE 2021-04-08
Software Developer (Python) - Adams-Brewer - Brockburgh, AE 2021-04-08
Futures trader - Schneider-Brady - North Jason, AE 2021-04-08
Tour manager - Gonzales-Frank - Arnoldhaven, AE 2021-04-08
Cytogeneticist - Smith-Wong - Lake Destiny, AP 2021-04-08
Designer, multimedia - Pierce-Herrera - South Timothyburgh, AP 2021-04-08
Trade union research officer - Aguilar, Rivera and Quinn - New Jimmyton, AE 2021-04-08
Chemist, analytical - Lowe, Barnes and Thomas - New Lucasbury, AP 2021-04-08
Programmer, multimedia - Lewis, Gonzalez and Vasquez - Port Cory, AE 2021-04-08
Engineer, broadcasting (operations) - Taylor PLC - Gileston, AA 2021-04-08
Teacher, primary school - Oliver, Jones and Ramirez - Cindyshire, AA 2021-04-08
Python Developer - Rivera and Sons - East Michaelfort, AA 2021-04-08
Manufacturing systems engineer - Garcia PLC - Joybury, AE 2021-04-08
Producer, television/film/video - Johnson, Wells and Kramer - Emmatown, AE 2021-04-08
Scientist, forensic - Gonzalez LLC - Colehaven, AP 2021-04-08
Bonds trader - Morgan, White and Macdonald - Port Coryton, AE 2021-04-08
Editorial assistant - Robinson-Fitzpatrick - Amyborough, AA 2021-04-08
Photographer - Waters, Wilson and Hoover - Reynoldsville, AA 2021-04-08
Retail banker - Hill LLC - Port Billy, AP 2021-04-08
Jewellery designer - Li-Gregory - Adamburgh, AA 2021-04-08
Ophthalmologist - Fisher, Ryan and Coleman - Wilsonmouth, AA 2021-04-08
Back-End Web Developer (Python, Django) - Stewart-Alexander - South Kimberly, AA 2021-04-08
Licensed conveyancer - Abbott and Sons - Benjaminland, AP 2021-04-08
Futures trader - Bryant, Santana and Davenport - Zacharyport, AA 2021-04-08
Counselling psychologist - Smith PLC - Port Devonville, AE 2021-04-08
Insurance underwriter - Patterson-Singh - East Thomas, AE 2021-04-08
Engineer, automotive - Martinez-Berry - New Jeffrey, AP 2021-04-08
Producer, radio - May, Taylor and Fisher - Davidside, AA 2021-04-08
Dispensing optician - Bailey, Owen and Thompson - Jamesville, AA 2021-04-08
Designer, fashion/clothing - Vasquez Ltd - New Kelly, AP 2021-04-08
Chartered loss adjuster - Leblanc LLC - Lake Antonio, AA 2021-04-08
Back-End Web Developer (Python, Django) - Jackson, Ali and Mckee - New Elizabethside, AA 2021-04-08
Forest/woodland manager - Blankenship, Knight and Powell - Millsbury, AE 2021-04-08
Clinical cytogeneticist - Patton, Haynes and Jones - Lloydton, AP 2021-04-08
Print production planner - Wood Inc - Port Jeremy, AA 2021-04-08
Systems developer - Collins Group - New Elizabethtown, AA 2021-04-08
Graphic designer - Flores-Nelson - Charlesstad, AE 2021-04-08
Writer - Mitchell, Jones and Olson - Josephbury, AE 2021-04-08
Field seismologist - Howard Group - Seanfurt, AA 2021-04-08
Chief Strategy Officer - Kramer-Edwards - Williambury, AA 2021-04-08
Air cabin crew - Berry-Houston - South Jorgeside, AP 2021-04-08
Python Programmer (Entry-Level) - Mathews Inc - Robertborough, AP 2021-04-08
Warden/ranger - Riley-Johnson - South Saratown, AP 2021-04-08
Sports therapist - Spencer and Sons - Hullview, AA 2021-04-08
Arts development officer - Camacho-Sanchez - Philipland, AP 2021-04-08
Printmaker - Oliver and Sons - North Patty, AE 2021-04-08
Health and safety adviser - Eaton PLC - North Stephen, AE 2021-04-08
Manufacturing systems engineer - Stanley-Frederick - Stevensland, AP 2021-04-08
Programmer, applications - Bradley LLC - Reyesstad, AE 2021-04-08
Medical physicist - Parker, Goodwin and Zavala - Bellberg, AP 2021-04-08
Media planner - Kim-Miles - North Johnland, AE 2021-04-08
Software Developer (Python) - Moreno-Rodriguez - Martinezburgh, AE 2021-04-08
Surveyor, land/geomatics - Brown-Ortiz - Joshuatown, AE 2021-04-08
Legal executive - Hartman PLC - West Ericstad, AA 2021-04-08
Librarian, academic - Brooks Inc - Tuckertown, AE 2021-04-08
Barrister - Washington-Castillo - Perezton, AE 2021-04-08
Museum/gallery exhibitions officer - Nguyen, Yoder and Petty - Lake Abigail, AE 2021-04-08
Radiographer, diagnostic - Holder LLC - Jacobshire, AP 2021-04-08
Database administrator - Yates-Ferguson - Port Susan, AE 2021-04-08
Furniture designer - Ortega-Lawrence - North Tiffany, AA 2021-04-08
Ship broker - Fuentes, Walls and Castro - Michelleville, AP 2021-04-08

In [6]:
import pandas as pd

datos = {
    "titulo": [],
    "empresa": [],
    "ubicacion": [],
    "fecha": []
}

for t in tarjetas:
    titulo = t.find("h2", class_="title is-5").text.strip()
    empresa = t.find("h3", class_="subtitle is-6 company").text.strip()
    ubicacion = t.find("p", class_="location").text.strip()
    fecha = t.find("time").text.strip()

    datos["titulo"].append(titulo)
    datos["empresa"].append(empresa)
    datos["ubicacion"].append(ubicacion)
    datos["fecha"].append(fecha)

df = pd.DataFrame(datos)
df

,titulo,empresa,ubicacion,fecha
0,Senior Python Developer,"Payne, Roberts and Davis","Stewartbury, AA",2021-04-08
1,Energy engineer,Vasquez-Davidson,"Christopherville, AA",2021-04-08
2,Legal executive,"Jackson, Chambers and Levy","Port Ericaburgh, AA",2021-04-08
3,Fitness centre manager,Savage-Bradley,"East Seanview, AP",2021-04-08
4,Product manager,Ramirez Inc,"North Jamieview, AP",2021-04-08
...,...,...,...,...
95,Museum/gallery exhibitions officer,"Nguyen, Yoder and Petty","Lake Abigail, AE",2021-04-08
96,"Radiographer, diagnostic",Holder LLC,"Jacobshire, AP",2021-04-08
97,Database administrator,Yates-Ferguson,"Port Susan, AE",2021-04-08
98,Furniture designer,Ortega-Lawrence,"North Tiffany, AA",2021-04-08
99,Ship broker,"Fuentes, Walls and Castro","Michelleville, AP",2021-04-08

In [8]:
df["ubicacion"].value_counts().sort_values(ascending=False)

ubicacion
Stewartbury, AA         1
Christopherville, AA    1
Port Ericaburgh, AA     1
East Seanview, AP       1
North Jamieview, AP     1
                       ..
Lake Abigail, AE        1
Jacobshire, AP          1
Port Susan, AE          1
North Tiffany, AA       1
Michelleville, AP       1
Name: count, Length: 100, dtype: int64

In [11]:
url = "https://www.themoviedb.org/movie"
response = requests.get(url)
sopa = BeautifulSoup(response.text, "lxml")

peliculas = sopa.find_all("img", alt=True)

datos = {"titulo": []}

for p in peliculas:
    titulo = p["alt"]
    datos["titulo"].append(titulo)

df = pd.DataFrame(datos)
df

                       titulo
0   The Movie Database (TMDB)
1                     Netflix
2          Amazon Prime Video
3                    Apple TV
4                 Disney Plus
..                        ...
95                     Malena
96                   Tayuan 2
97                       Rita
98                   Venganza
99  The Movie Database (TMDB)

[100 rows x 1 columns]

In [12]:
import requests

API_KEY = "TU_API_KEY"

url = f"https://api.themoviedb.org/3/movie/popular?api_key={API_KEY}&language=es-ES&page=1"
resp = requests.get(url).json()

for p in resp["results"]:
    print(p["title"], "-", p["release_date"])

KeyError: 'results'

In [14]:
import requests

API_KEY = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXJ0YS5oYXJhbmFAZ21haWwuY29tIiwianRpIjoiYTdjYWI0NWItMzYwOS00Y2M0LWFhZTQtMDdjMmYyN2YwMjJjIiwiaXNzIjoiQUVNRVQiLCJpYXQiOjE3NzY0NDYyNzMsInVzZXJJZCI6ImE3Y2FiNDViLTM2MDktNGNjNC1hYWU0LTA3YzJmMjdmMDIyYyIsInJvbGUiOiIifQ.UcX_F5DOUrwvu9wk7-tKGchx475DaYJSj5cFpxn2Xws"

url = "https://opendata.aemet.es/opendata/api/prediccion/especifica/playa/5200103"

querystring = {"api_key": API_KEY}

response = requests.get(url, params=querystring)
data = response.json()

In [15]:
url_datos = data["datos"]

In [16]:
response_datos = requests.get(url_datos)
datos_reales = response_datos.json()

In [18]:
for d in dias:
    print(d.keys())
    break

dict_keys(['estadoCielo', 'viento', 'oleaje', 'tMaxima', 'sTermica', 'tAgua', 'uvMax', 'fecha', 'tmaxima', 'stermica', 'tagua'])

In [24]:
for d in dias:
    print(d["estadoCielo"])
    break

{'value': '', 'f1': 100, 'descripcion1': 'despejado', 'f2': 100, 'descripcion2': 'despejado'}

In [25]:
def get_estado_cielo(d):
    ec = d.get("estadoCielo", {})
    if isinstance(ec, dict):
        return ec.get("descripcion1") or ec.get("descripcion2") or "Sin datos"
    return "Sin datos"

datos = {
    "fecha": [],
    "t_max": [],
    "sensacion_termica": [],
    "t_agua": [],
    "uv_max": [],
    "estado_cielo": []
}

for d in dias:
    datos["fecha"].append(d["fecha"])
    datos["t_max"].append(d.get("tmaxima"))
    datos["sensacion_termica"].append(d.get("stermica"))
    datos["t_agua"].append(d.get("tagua"))
    datos["uv_max"].append(d.get("uvMax"))
    datos["estado_cielo"].append(get_estado_cielo(d))

df = pd.DataFrame(datos)
df

,fecha,t_max,sensacion_termica,t_agua,uv_max,estado_cielo
0,20260514,"{'value': '', 'valor1': 24}","{'value': '', 'valor1': 450, 'descripcion1': '...","{'value': '', 'valor1': 19}","{'value': '', 'valor1': 9}",despejado
1,20260515,"{'value': '', 'valor1': 23}","{'value': '', 'valor1': 450, 'descripcion1': '...","{'value': '', 'valor1': 18}","{'value': '', 'valor1': 8}",despejado
2,20260516,"{'value': '', 'valor1': 22}","{'value': '', 'valor1': 450, 'descripcion1': '...","{'value': '', 'valor1': 18}","{'value': '', 'valor1': 8}",nuboso

In [26]:
import pandas as pd

def extraer_valor(d):
    if isinstance(d, dict):
        return d.get("valor1", None)
    return None

def get_estado_cielo(d):
    ec = d.get("estadoCielo", {})
    if isinstance(ec, dict):
        return ec.get("descripcion1") or ec.get("descripcion2") or "Sin datos"
    return "Sin datos"

datos = {
    "fecha": [],
    "t_max": [],
    "sensacion_termica": [],
    "t_agua": [],
    "uv_max": [],
    "estado_cielo": []
}

for d in dias:
    datos["fecha"].append(d["fecha"])
    datos["t_max"].append(extraer_valor(d.get("tmaxima")))
    datos["sensacion_termica"].append(extraer_valor(d.get("stermica")))
    datos["t_agua"].append(extraer_valor(d.get("tagua")))
    datos["uv_max"].append(extraer_valor(d.get("uvMax")))
    datos["estado_cielo"].append(get_estado_cielo(d))

df = pd.DataFrame(datos)
df

      fecha  t_max  sensacion_termica  t_agua  uv_max estado_cielo
0  20260514     24                450      19       9    despejado
1  20260515     23                450      18       8    despejado
2  20260516     22                450      18       8       nuboso

In [31]:
df["fecha"] = pd.to_datetime(df["fecha"], format="%Y%m%d")

In [32]:
df

       fecha  t_max  sensacion_termica  t_agua  uv_max estado_cielo
0 2026-05-14     24                450      19       9    despejado
1 2026-05-15     23                450      18       8    despejado
2 2026-05-16     22                450      18       8       nuboso

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   fecha              3 non-null      datetime64[us]
 1   t_max              3 non-null      int64
 2   sensacion_termica  3 non-null      int64
 3   t_agua             3 non-null      int64
 4   uv_max             3 non-null      int64
 5   estado_cielo       3 non-null      str
dtypes: datetime64[us](1), int64(4), str(1)
memory usage: 276.0 bytes